name: Latest blog post workflow
on:
  schedule: 
    - cron: '0 * * * *' 
  workflow_dispatch: 

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Pull in blog posts
        uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "https://dev.to/feed/everlygif,https://medium.com/feed/@everlyprecia"
          max_post_count: 10
